### ISSUE TITLE
Unable to access website

### ISSUE THREAD

**Issue by aawink7** [BCV-Uniandes/Bonet#3]
Thank you for your work!

I would like to access the RHPE dataset, but I couldn't open the link that was provided. 
Could you check if there's some issue with the website?

Thanks a lot

**Comment by Arki99** [comment]
Yeah, I have been experiencing the same issue. Would be great if the website is up and running.
Thanks a lot @mc-escobar11

**Comment by mc-escobar11** [comment]
Hello @aawink7 @Arki99 
We apollogize for the late reply. Due to the current global situation we have been having some technical difficulties with out website services. However, you can download our Bone Age Assessment resources using this link http://marr.uniandes.edu.co/carpos/images/examples/datasets/  and If you need to evaluate a method through our evaluation server please send an email to mc.escobar11@uniandes.edu.co
We will notify you when our website is up again
Thank you

**Comment by aawink7** [comment]
No worries, completely understand!
Thank you so much for this link @mc-escobar11
